language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2"

install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    # 1.1 Semver check
    - stage: test
      jdk: openjdk11
      script: ./mvnw verify -Pcheck-semantic-version -DskipTests=true -DskipITs=true -Darchetype.test.skip=true
      env: CHECK_SEMANTIC_VERSION=true

    # 1.2 Tests
    - stage: test
      jdk: openjdk11
      script: ./mvnw verify
      env: VERIFY=true

      # 1.3 Coverage
    - stage: test
      jdk: openjdk11
      script: ./mvnw jacoco:prepare-agent verify jacoco:report coveralls:report
      env: COVERAGE=true

    # 1.4 Javadoc
    - jdk: openjdk11
      env: JAVADOC=true
      script:
        - ./mvnw javadoc:jar


branches:
  only:
    - master
    - develop
